const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
let reports=[],topics=[],products=[],currentReport='',currentTopic='',activeView='reports';
const STATIC_MODE=true||location.hostname==='cdn.jsdelivr.net'||location.hostname==='raw.githack.com';
const STATIC_DATA='https://raw.githubusercontent.com/15236702150master/qq-hourly-intel-live/gh-pages/data/';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(url,label)=>url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label||url)}</a>`:esc(label||'');
function md(s){let x=esc(s);x=x.replace(/(https?:\/\/[^\s<`，。；：)）\]]+)/g,'<a href="$1" target="_blank" rel="noopener noreferrer">$1</a>');x=x.replace(/^### (.*)$/gm,'<h3>$1</h3>').replace(/^## (.*)$/gm,'<h2>$1</h2>').replace(/^# (.*)$/gm,'<h1>$1</h1>').replace(/^> (.*)$/gm,'<blockquote>$1</blockquote>').replace(/^[-*] (.*)$/gm,'<li>$1</li>').replace(/(<li>.*<\/li>\n?)+/g,m=>'<ul>'+m+'</ul>').replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/\n{2,}/g,'<br><br>').replace(/\n/g,'<br>');return x}
function setView(view){activeView=view;$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$$('.view').forEach(x=>x.classList.toggle('active',x.id===view+'-view'));$('.toolbar').hidden=view==='ask';const labels={reports:['LATEST BRIEFING','最近一小时发生了什么'],resources:['KNOWLEDGE LIBRARY','可复用资源专题'],products:['PRICE BOARD','同类商品与报价'],ask:['ASK THE ARCHIVE','查询最近三天资料']};$('#view-kicker').textContent=labels[view][0];$('#view-title').textContent=labels[view][1];fillFilter();render()}
function fillFilter(){const old=$('#filter').value;let values=[];if(activeView==='resources')values=topics.map(x=>x.name);if(activeView==='products')values=[...new Set(products.map(x=>x.category))];$('#filter').innerHTML='<option value="">全部</option>'+values.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');$('#filter').value=values.includes(old)?old:''}
function query(){return $('#search').value.trim().toLowerCase()}
function render(){if(activeView==='reports')renderReports();if(activeView==='resources')renderTopics();if(activeView==='products')renderProducts()}
function renderReports(){const q=query();const list=reports.filter(r=>!q||(r.title+' '+r.markdown+' '+(r.topics||[]).join(' ')).toLowerCase().includes(q));$('#visible-count').textContent=list.length;$('#report-list').innerHTML=list.length?list.map(r=>`<button class="list-row ${r.id===currentReport?'active':''}" data-report="${r.id}"><time>${esc(r.period_start?`${r.period_start.slice(5,16)} - ${r.period_end.slice(11,16)}`:r.created_at)}</time><strong>${esc(r.title)}</strong><small>${r.message_count} 条消息 · ${r.group_count} 个群</small></button>`).join(''):'<div class="empty">没有匹配的简报</div>';$$('[data-report]').forEach(b=>b.onclick=()=>openReport(b.dataset.report))}
async function openReport(id){currentReport=id;const r=STATIC_MODE?reports.find(x=>x.id===id):await (await fetch('/api/reports/'+encodeURIComponent(id))).json();if(!r)return;const period=r.period_start?`${r.period_start} 至 ${r.period_end}`:r.created_at;$('#reader-head').innerHTML=`<div><p class="kicker">HOURLY REPORT</p><h2>${esc(period)}</h2><div class="chips"><span class="chip">${r.message_count} 条消息</span><span class="chip">${r.group_count} 个群</span>${(r.resource_topics||[]).map(x=>`<button class="chip topic-link" data-topic-link="${esc(x)}">${esc(x)}</button>`).join('')}</div></div>`;$('#reader-body').innerHTML='<div class="markdown">'+md(r.markdown)+'</div>';$$('[data-topic-link]').forEach(b=>b.onclick=()=>openTopic(b.dataset.topicLink));history.replaceState(null,'','?report='+encodeURIComponent(id));renderReports()}
function renderTopics(){const q=query(),chosen=$('#filter').value;const list=topics.filter(x=>(!chosen||x.name===chosen)&&(!q||x.name.toLowerCase().includes(q)));$('#topic-count').textContent=list.length;$('#topic-list').innerHTML=list.length?list.map(x=>`<button class="list-row ${x.name===currentTopic?'active':''}" data-topic="${esc(x.name)}"><strong>${esc(x.name)}</strong><small>${x.count} 项 · 更新 ${esc(x.updated_at)}</small></button>`).join(''):'<div class="empty">暂无匹配专题</div>';$$('[data-topic]').forEach(b=>b.onclick=()=>loadTopic(b.dataset.topic));if(!currentTopic&&list.length)loadTopic(list[0].name)}
async function loadTopic(name){currentTopic=name;const data=STATIC_MODE?{resources:(window.library.resources||[]).filter(x=>x.topic===name)}:await (await fetch('/api/topics/'+encodeURIComponent(name))).json();$('#topic-head').innerHTML=`<div><p class="kicker">RESOURCE TOPIC</p><h2>${esc(name)}</h2><p class="muted">${data.resources.length} 项已整理资源</p></div>`;$('#resource-list').innerHTML=data.resources.length?data.resources.map(resourceCard).join(''):'<div class="empty large">该专题暂无资源</div>';renderTopics()}
function openTopic(name){setView('resources');$('#filter').value=name;currentTopic='';loadTopic(name)}
function resourceCard(r){const source=r.sources?.at(-1)||{};return `<section class="resource-row"><div class="resource-main"><p class="type">${esc(r.file_name?'文件':'链接')} · 提及 ${r.mentions} 次</p><h3>${r.url?link(r.url,r.title):esc(r.title)}</h3><p>${esc(r.purpose||'用途待补充')}</p>${r.file_name?`<code>${esc(r.file_name)}</code>`:''}${r.notes?`<p class="muted">${esc(r.notes)}</p>`:''}</div><div class="source"><strong>${esc(source.group||'来源群未标注')}</strong><span>${source.nickname_url?link(source.nickname_url,source.nickname):esc(source.nickname||'昵称未标注')}</span><time>${esc(source.time||r.last_seen)}</time></div></section>`}
function renderProducts(){const q=query(),chosen=$('#filter').value;const list=products.filter(x=>(!chosen||x.category===chosen)&&(!q||(x.category+' '+x.name+' '+x.seller+' '+x.details).toLowerCase().includes(q)));const groups=Object.groupBy?Object.groupBy(list,x=>`${x.category} · ${x.direction||'报价'} · ${x.unit||'单位未说明'}`):list.reduce((a,x)=>((a[`${x.category} · ${x.direction||'报价'} · ${x.unit||'单位未说明'}`]??=[]).push(x),a),{});$('#product-groups').innerHTML=Object.keys(groups).length?Object.entries(groups).map(([name,items])=>`<section class="product-section"><header><h2>${esc(name)}</h2><span>${items.length} 个来源</span></header><div class="product-table">${items.map(productRow).join('')}</div></section>`).join(''):'<div class="empty large">暂无匹配商品</div>'}
function productRow(p){const source=p.sources?.at(-1)||{};const price=p.price!==null&&p.price!==undefined?`${esc(p.currency==='CNY'?'¥':p.currency)}${esc(p.price)}${p.unit?'/'+esc(p.unit):''}`:esc(p.price_text||'价格未说明');const sellerUrl=p.seller_url||source.nickname_url;return `<article class="product-row ${p.is_lowest?'lowest':''}"><div class="rank">${p.is_lowest?'<span>最低价</span>':'<span>报价</span>'}<strong>${price}</strong></div><div class="product-info"><h3>${p.link?link(p.link,p.name):esc(p.name)}</h3><p>${esc(p.details||'规格未说明')}</p></div><div class="seller"><small>${esc(source.group||'来源群未标注')}</small><strong>${sellerUrl?link(sellerUrl,p.seller||source.nickname):esc(p.seller||source.nickname||'卖家未标注')}</strong><time>${esc(source.time||p.last_seen)}</time></div></article>`}
async function askArchive(event){event.preventDefault();const question=$('#question').value.trim();if(!question)return;if(STATIC_MODE){$('#answer').innerHTML='<div class="empty large">公网页面展示已整理快照；资料库问答请打开电脑上的局域网地址。</div>';return}const button=$('#ask-form button');button.disabled=true;button.textContent='查询中';$('#answer').innerHTML='<div class="empty large">正在检索最近三天聊天与商品资源库…</div>';try{const response=await fetch('/api/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question})});const data=await response.json();if(!response.ok)throw new Error(data.detail||'查询失败');$('#answer').innerHTML='<div class="markdown">'+md(data.answer)+'</div>'}catch(e){$('#answer').innerHTML=`<div class="empty large">${esc(e.message)}</div>`}button.disabled=false;button.textContent='查询'}
async function load(){try{let rd,lib,pd;if(STATIC_MODE){const fresh='?v='+Date.now();[rd,lib,pd]=await Promise.all([fetch(STATIC_DATA+'reports.json'+fresh,{cache:'no-store'}).then(r=>r.json()),fetch(STATIC_DATA+'library.json'+fresh,{cache:'no-store'}).then(r=>r.json()),fetch(STATIC_DATA+'products.json'+fresh,{cache:'no-store'}).then(r=>r.json())]);window.library=lib;rd={reports:rd,connected:false}}else{[rd,lib,pd]=await Promise.all([fetch('/api/reports').then(r=>r.json()),fetch('/api/library').then(r=>r.json()),fetch('/api/products').then(r=>r.json())])}reports=rd.reports||[];topics=lib.topics||[];products=pd.products||[];$('#connection').textContent=STATIC_MODE?'公网实时快照':(rd.connected?'QQ 已连接':'等待 QQ 连接');$('#report-count').textContent=`${reports.length} 份简报`;$('#resource-count').textContent=`${lib.resource_count||0} 项资源`;$('#product-count').textContent=`${lib.product_count||0} 个商品`;fillFilter();render();const requested=new URLSearchParams(location.search).get('report');if(activeView==='reports'&&!currentReport&&reports.length)openReport(reports.some(r=>r.id===requested)?requested:reports[0].id)}catch(e){$('#connection').textContent='页面数据未连接'}}
$$('.tab').forEach(x=>x.onclick=()=>setView(x.dataset.view));$('#search').oninput=render;$('#filter').onchange=render;$('#refresh').onclick=load;$('#ask-form').onsubmit=askArchive;load();setInterval(load,60000);

